#! /bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# Border
bspc config focused_border_color  "#6c71c4"
bspc config normal_border_color   "#073642"
bspc config active_border_color   "#073642"

## Autostart ##
bash ~/.config/polybar/launch.sh &
# notifs
/usr/bin/dunst &
# polkit 
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# wallpaper
WALLPAPER_DIR=~/Pictures/wallpapers
feh --bg-scale $WALLPAPER_DIR/$(ls $WALLPAPER_DIR | shuf -n 1)

# picom
picom -b &
# NetworkManager applet
nm-applet --indicator &

# audio stuff
pipewire &
pipewire-pulse &
wireplumber &

xsetroot -cursor_name left_ptr &
# low battery notifier (laptop moment)
# ~/.config/bspwm/scripts/low_bat_notifier.sh

# make AWT work
export _JAVA_AWT_WM_NONREPARTENTING=1
